/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/ProtectedRoute'
import { Route as NavigationsImport } from './routes/Navigations'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProtectedRouteRoute = ProtectedRouteImport.update({
  path: '/ProtectedRoute',
  getParentRoute: () => rootRoute,
} as any)

const NavigationsRoute = NavigationsImport.update({
  path: '/Navigations',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Navigations': {
      id: '/Navigations'
      path: '/Navigations'
      fullPath: '/Navigations'
      preLoaderRoute: typeof NavigationsImport
      parentRoute: typeof rootRoute
    }
    '/ProtectedRoute': {
      id: '/ProtectedRoute'
      path: '/ProtectedRoute'
      fullPath: '/ProtectedRoute'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  NavigationsRoute,
  ProtectedRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/Navigations",
        "/ProtectedRoute"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Navigations": {
      "filePath": "Navigations.tsx"
    },
    "/ProtectedRoute": {
      "filePath": "ProtectedRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
