/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthPoIndexImport } from './routes/_auth/po/index'
import { Route as AuthPoCreateImport } from './routes/_auth/po/create'

// Create Virtual Routes

const AuthIndexLazyImport = createFileRoute('/_auth/')()
const AuthProjectIndexLazyImport = createFileRoute('/_auth/project/')()
const AuthProjectCreateLazyImport = createFileRoute('/_auth/project/create')()

// Create/Update Routes

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))

const AuthProjectIndexLazyRoute = AuthProjectIndexLazyImport.update({
  path: '/project/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/project/index.lazy').then((d) => d.Route),
)

const AuthPoIndexRoute = AuthPoIndexImport.update({
  path: '/po/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjectCreateLazyRoute = AuthProjectCreateLazyImport.update({
  path: '/project/create',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/project/create.lazy').then((d) => d.Route),
)

const AuthPoCreateRoute = AuthPoCreateImport.update({
  path: '/po/create',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/po/create': {
      id: '/_auth/po/create'
      path: '/po/create'
      fullPath: '/po/create'
      preLoaderRoute: typeof AuthPoCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/project/create': {
      id: '/_auth/project/create'
      path: '/project/create'
      fullPath: '/project/create'
      preLoaderRoute: typeof AuthProjectCreateLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/po/': {
      id: '/_auth/po/'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof AuthPoIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/project/': {
      id: '/_auth/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthProjectIndexLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthIndexLazyRoute,
    AuthPoCreateRoute,
    AuthProjectCreateLazyRoute,
    AuthPoIndexRoute,
    AuthProjectIndexLazyRoute,
  }),
  SigninRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/signin"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/po/create",
        "/_auth/project/create",
        "/_auth/po/",
        "/_auth/project/"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/po/create": {
      "filePath": "_auth/po/create.tsx",
      "parent": "/_auth"
    },
    "/_auth/project/create": {
      "filePath": "_auth/project/create.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/po/": {
      "filePath": "_auth/po/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/project/": {
      "filePath": "_auth/project/index.lazy.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
